const codes = {
    BAD_REQUEST: "BAD_REQUEST" as const,
    UNAUTHORIZED: "UNAUTHORIZED" as const,
    UNAUTHENTICATED: "UNAUTHENTICATED" as const,
    FORBIDDEN: "FORBIDDEN" as const,
    NOT_FOUND: "NOT_FOUND" as const,
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR" as const,

    LOGGED_IN: "LOGGED_IN" as const,
    LOGGED_OUT: "LOGGED_OUT" as const,
    SESSION_RECOVERED: "SESSION_RECOVERED" as const,
    USER_FETCHED: "USER_FETCHED" as const,
    USER_CREATED: "USER_CREATED" as const,
    USER_UPDATED: "USER_UPDATED" as const,
    PASSWORD_RECOVERY_SENT: "PASSWORD_RECOVERY_SENT" as const,

    DOCUMENT_SAVED: "DOCUMENT_SAVED" as const,
    DOCUMENT_DELETED: "DOCUMENT_DELETED" as const,
    DOCUMENT_FETCHED: "DOCUMENT_FETCHED" as const,
    DOCUMENTS_FETCHED: "DOCUMENTS_FETCHED" as const,
    DOCUMENT_DOWNLOADED: "DOCUMENT_DOWNLOADED" as const,

    CHUNK_SAVED: "CHUNK_SAVED" as const,

    FOLDER_SAVED: "FOLDER_SAVED" as const,
    FOLDER_DELETED: "FOLDER_DELETED" as const,
    FOLDER_FETCHED: "FOLDER_FETCHED" as const,
    FOLDERS_FETCHED: "FOLDERS_FETCHED" as const,
    FOLDER_STATS_FETCHED: "FOLDER_STATS_FETCHED" as const,
};

export default codes;
